name: Build Variant Book

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install chess requests

      - name: Run filter_and_build.py
        run: python filter_and_build.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: book-artifacts
          path: |
            horde.bin
